include:
  - local: .helper/gitlab-ci/tofu/.common.yaml
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/base.yaml"
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/versioning.yaml"
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/helm-packaging.yaml"
  - project: "common-device-management/utils/templates/gitlab-ci"
    ref: main
    file: "shared/dev-deployment.yaml"


stages:
  - check
  - test
  - version
  - tofu
  - deploy
  - upload
  - dev-deployment
  
variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: "$CODE_NO_PROXY,captain.rtf.siemens.net,falcon.rtf-alm.siemens.cloud,xorcery.dema-platform.siemens.cloud"
  HTTP_PROXY: $http_proxy
  HTTPS_PROXY: $http_proxy
  NO_PROXY: "$no_proxy"

  AWS_ACCOUNT_ID: $DEV_AWS_ACCOUNT_ID
  TF_VAR_JWT_ROLE_NAME: $DEV_TF_VAR_JWT_ROLE_NAME
  PROD_AWS_ACCOUNT_ID: $PROD_AWS_ACCOUNT_ID
  TF_VAR_repository: $CI_PROJECT_PATH
  TF_VAR_config_file_path: $config
  
  COMPONENT_NAME: updatehub


###########################################################################################################################################
### Tofu (Terraform)
### Stage: tofu & tofu-destroy
###########################################################################################################################################

# UpdateHub

dev:update-hub:plan:
  extends: .common-tofu
  script:
    - tofu plan -var-file="tfvars/${TF_VARFILE}" -out=${TF_PLANFILE} -lock="${LOCK_FLAG}"
  artifacts:
    paths:
      - ${TF_FOLDER}/${TF_PLANFILE}
  rules:
    - changes:
      - tofu/**/* # all files under folder
      when: on_success

dev:update-hub:apply:
  needs:
    - dev:update-hub:plan
  extends: .common-tofu
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
  script:
    - tofu apply -input=false -lock="${LOCK_FLAG}" ${TF_PLANFILE}
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: never
    - changes:
      - tofu/**/* # all files under folder
      when: manual

dev:update-hub:destroy:
  extends: .common-tofu
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - tofu plan -destroy -var-file="tfvars/${TF_VARFILE}" -var-file="tfvars/ci.tfvars" -out=${TF_PLANFILE} -lock="${LOCK_FLAG}"
    - tofu apply -input=false -lock="${LOCK_FLAG}" ${TF_PLANFILE}
  rules:
    # Only main and tags
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: never
    # Only if explicitly triggered and variable is set
    - if: $CI_PIPELINE_SOURCE == "web" && $DESTROY_RESOURCE == "true"
      when: manual


###########################################################################################################################################
### Stage: deploy
###########################################################################################################################################

deploy:
  stage: deploy
  extends: .common-tofu
  variables:
    FILE: "${CI_PROJECT_DIR}/tofu/templates/irs-task-definition.json"
    PORT: 8080
    NAME: "$COMPONENT_NAME"
    ECS_TASK_FAMILY: "irs-service-task"

    IMAGE_LOCATION: ghcr.io/industrial-asset-hub/irs
  before_script: 
    - !reference [.common-tofu, before_script]
    - |
      ecs_task_execution_role_arn=$(tofu output -raw -var-file="tfvars/${TF_VARFILE}" ecs_task_execution_role_arn)
      github_pat_secret_arn=$(tofu output -raw -var-file="tfvars/${TF_VARFILE}" github_pat_secret_arn)
      irs_log_group_name=$(tofu output -raw -var-file="tfvars/${TF_VARFILE}" irs_log_group_name)
      aws_ecs_cluster_name=$(tofu output -raw -var-file="tfvars/${TF_VARFILE}" aws_ecs_cluster_name)
      aws_ecs_service_name=$(tofu output -raw -var-file="tfvars/${TF_VARFILE}" aws_ecs_service_name)

      IMAGE="ghcr.io/industrial-asset-hub/irs:latest"
      if [ $DIGIST ]; then
        IMAGE="ghcr.io/industrial-asset-hub/irs@sha256:${DIGIST}"
      fi
  script: |
    cat <<< $(jq --arg ecs_task_execution_role_arn "$ecs_task_execution_role_arn" '.executionRoleArn=$ecs_task_execution_role_arn' $FILE ) > $FILE
    cat <<< $(jq --arg NAME "$NAME" '.containerDefinitions[0].name=$NAME' $FILE ) > $FILE
    cat <<< $(jq --arg IMAGE "$IMAGE" '.containerDefinitions[0].image=$IMAGE' $FILE ) > $FILE
    cat <<< $(jq --arg github_pat_secret_arn "$github_pat_secret_arn" '.containerDefinitions[0].repositoryCredentials.credentialsParameter=$github_pat_secret_arn' $FILE ) > $FILE
    cat <<< $(jq --arg irs_log_group_name "$irs_log_group_name" '.containerDefinitions[0].logConfiguration.options."awslogs-group"=$irs_log_group_name' $FILE ) > $FILE
    cat <<< $(jq --arg AWS_REGION "$AWS_REGION" '.containerDefinitions[0].logConfiguration.options."awslogs-region"=$AWS_REGION' $FILE ) > $FILE
    cat <<< $(jq --argjson PORT "$PORT" '.containerDefinitions[0].portMappings[0].containerPort=$PORT' $FILE ) > $FILE
    cat <<< $(jq --arg PORT "curl -f http://localhost:${PORT}/swagger/index.html || exit 1" '.containerDefinitions[0].healthCheck.command[1]=$PORT' $FILE ) > $FILE

    export TASK_REVISION=$(aws ecs register-task-definition \
      --family "$ECS_TASK_FAMILY" \
      --cli-input-json file://$FILE \
      --region $AWS_REGION | jq --raw-output '.taskDefinition.revision')

    echo "Registered ECS Task Definition = "$TASK_REVISION
    echo "Updated Task Definition = $ECS_TASK_FAMILY:"$TASK_REVISION

    UPDATE_ECS_SERVICE=$(aws ecs update-service \
      --cluster $aws_ecs_cluster_name \
      --service $aws_ecs_service_name \
      --task-definition $ECS_TASK_FAMILY:$TASK_REVISION \
      --desired-count 1 \
      --region $AWS_REGION \
      --force-new-deployment | jq --raw-output '.service.serviceName')

    echo "Deployment of $UPDATE_ECS_SERVICE has been completed"

###########################################################################################################################################
### Stage: upload
###########################################################################################################################################

createHelmPackage:
  extends: .package_push_helmchart
  needs: ["version"]

###########################################################################################################################################
### Stage: dev-deployment
###########################################################################################################################################

commitToUmbrella:
  needs: ["version", "createHelmPackage"]
  variables:
    BRANCH_TARGET_BRANCH: "fx/update-hub"
    MAIN_TARGET_BRANCH: "fx/update-hub"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG
      exists:
        - "**/Chart.yaml"
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      exists:
        - "**/Chart.yaml"
      when: on_success
      allow_failure: true

