apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "updatehub.fullname" . }}
  labels:
    {{- include "updatehub.labels" . | nindent 4 }}
    {{- tpl (toYaml .Values.global.deployment.labels) . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "updatehub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "updatehub.selectorLabels" . | nindent 8 }}
        {{- tpl (toYaml .Values.global.deployment.labels) . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "updatehub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENABLE_METRIC
              value: "true"
            - name: OTLP_ENDPOINT_URL
              value: "http://datadog.datadog.svc.cluster.local:4317"
            {{- if .Values.args.configFilePath }}
            - name: CONFIG_FILE_PATH
              value: "{{ .Values.args.configFilePath }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.args.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
