{{- if not .Values.localstack.enabled }}
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: {{ include "updatehub.s3Name" . }}
  labels:
    name: {{ include "updatehub.s3Name" . }}
  annotations:
    crossplane.io/external-name: {{ include "updatehub.s3ExternalName" . }}
spec:
  forProvider:
    assumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::{{ int .Values.global.k8sCluster.awsAccountId }}:oidc-provider/{{ .Values.global.k8sCluster.oidc }}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "{{ .Values.global.k8sCluster.oidc }}:sub": "system:serviceaccount:{{ .Release.Namespace }}:{{ include "updatehub.serviceAccountName" . }}"
                }
              }
            }
          ]
        }
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ include "updatehub.s3Name" . }}
  labels:
    name: {{ include "updatehub.s3Name" . }}
spec:
  forProvider:
    name: {{ include "updatehub.s3ExternalName" . }}
    document: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:DeleteObjectVersion",
                "s3:ListBucketVersions"
              ],
              "Resource": [
                "arn:aws:s3:::{{ .Values.args.s3BucketName }}",
                "arn:aws:s3:::{{ .Values.args.s3BucketName }}/*"
              ]
            }
          ]
        }

---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ include "updatehub.s3Name" . }}
  labels:
    name: {{ include "updatehub.s3Name" . }}
spec:
  forProvider:
    roleNameSelector:
      matchLabels:
        name: {{ include "updatehub.s3Name" . }}
    policyArnSelector:
      matchLabels:
        name: {{ include "updatehub.s3Name" . }}
{{- end }}
