aas-servers:

- name: SampleAASQLServer
  id-link-prefix: https://i.siemens.com/
  url: your-AAS-server-URL
  auth:

- name: SampleAasServerOAuth2
  id-link-prefix: https://sample-company-1.com/
  url: https://sample-company-1.com/aas
  auth:
    auth-type: oauth2
    client-id: your-client-id
    client-secret: your-client-secret
    token-url: https://sample-company-1.com/auth/realms/realm1/protocol/openid-connect/token

- name: SampleAasServerApiKey
  id-link-prefix: https://sample-company-2.com/
  url: https://sample-company-1.com/products/aas
  auth:
    auth-type: apikey
    api-key: your-api-key

- name: SampleAasServerBearerToken
  id-link-prefix: https://sample-company-2.com/
  url: https://sample-company-1.com/products/aas
  auth:
    auth-type: bearertoken
    bearer-token: your-bearer-token

- name: SampleAasServerHilscherLogin
  id-link-prefix: https://sample-company-2.com/
  version: v30 # v30 or basyx (default)
  url: https://sample-company-1.com/products/aas
  discovery-url: https://sample-company-1.com/products/aas/v3.0 # Only used for v30
  auth:
      auth-type: hilscher
      client-id: my-client-id
      secret: my-secret
      login-url: https://hilscher-aas.netiot.com/login

- name: SampleAasServerv30
  id-link-prefix: https://sample-company-2.com/
  version: v30 # v30 or basyx (default)
  url: https://sample-company-1.com/products/aas
  discovery-url: https://sample-company-1.com/products/aas/v3.0 # Only used for v30
  auth:

irs:
  url: https://irs-sample-server.de/irs
  username: my-username
  password: my-password
