# .github/workflows/deploy.yml

name: Deploy Terraform with Tofu

on:
  push:

env:
  AWS_IAM_ROLE_TOFU: ${{ vars.AWS_IAM_ROLE_TOFU }}
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Deploy Infrastructure with Tofu
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Needed to use OIDC authentication
      contents: read   # Allows reading repository contents

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials with OIDC
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_TOFU }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: terraform plan
        uses: dflook/tofu-plan@v1.44.0
        with:
          path: tofu
          backend_config: |
            bucket=state-bucket-${{ env.AWS_ACCOUNT_ID }}
            region=${{ env.AWS_DEFAULT_REGION }}
            key=${{ github.GITHUB_REPOSITORY }}-tfstate
          variables: |
            image = "ghcr.io/industrial-asset-hub/irs@sha256:1b2459561081860c472b214eeedf9be8d9be98bc31d8f649f93842193029707d"
            container_port = 8080
            vpc_id = "vpc-03dd3bac134a6b179"
            public_subnet_ids = '["subnet-02c27ec94ed4346ee", "subnet-0298ca4983a962864"]'
            private_subnet_ids = '["subnet-0cffb439f8c1ca584", "subnet-08f3f06d5b6dff6a6"]'
            repository = ${{ github.GITHUB_REPOSITORY }}
            domain_name = "cdm-dev.xo.siemens.cloud"
            github_pat_token = ${{ secrets.PAT_AWSREADREGISTRY }}
            ithub_pat_username = "florian.gerdes@siemens.com"