# .github/workflows/deploy.yml

name: Deploy Terraform with Tofu

on:
  push:

env:
  AWS_IAM_ROLE_TOFU: ${{ vars.AWS_IAM_ROLE_TOFU }}
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Deploy Infrastructure with Tofu
    runs-on: ubuntu-latest

    container:
      image: bridgecrew/tofu:latest  # Use the Tofu Docker image with Terraform pre-installed

    permissions:
      id-token: write  # Needed to use OIDC authentication
      contents: read   # Allows reading repository contents

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials with OIDC
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_TOFU }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Initialize Terraform
      - name: Terraform Init
        working-directory: ./tofu
        run: |
          terraform init \
            -backend-config "bucket=state-bucket-${{ env.AWS_ACCOUNT_ID }}" \
            -backend-config "region=${{ env.AWS_DEFAULT_REGION }}" \
            -backend-config "key=${{ github.GITHUB_REPOSITORY }}-tfstate"

      # Apply Terraform configuration using Tofu
      - name: Terraform Apply with Tofu
        working-directory: ./tofu
        run: |
          tofu run terraform apply -auto-approve
        if: github.ref == 'refs/heads/master'

      # Optional: Output Terraform state or other results
      - name: Show Terraform Outputs
        working-directory: ./tofu
        run: terraform output
        if: github.ref == 'refs/heads/master'
